name: education_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # =========================================================
  # ðŸ”‘ YANGILANGAN FIREBASE KUTUBXONALARI (BIR XIL VERSION QATORIDA)
  # =========================================================
  # Bularning barchasi (2.24.x) versiyasiga asoslangan edi.
  # Uni barchasi uchun bir xil versiya qatoriga o'tkazdik (masalan, 10.x yoki 11.x)
  url_launcher: ^6.2.5

  firebase_core: ^4.3.0      # Asosiy: Boshqa barcha Firebase kutubxonalari bunga moslashadi
  firebase_auth: ^6.1.3      # Authentication
  cloud_firestore: ^6.1.1    # Firestore DB
  firebase_storage: ^13.0.5   # 11.6.0 bu core 2.x bilan ishlaydigan eng yangi stabil versiya.

  # UI Kutubxonalari
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_rating_bar: ^4.0.1

  # Media va Chart Kutubxonalari
  video_player: ^2.10.1
  fl_chart: ^1.1.1
  flutter_local_notifications: ^19.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true